"""Seed 100+ Ayurvedic remedies into MongoDB."""

import asyncio
from app.database import init_db
from app.models.remedy import Remedy, Ingredient


REMEDIES_DATA = [
    # ── Respiratory ──
    {"disease_name": "Cough & Cold", "title": "Tulsi & Ginger Kadha", "short_description": "An ancient immunity-boosting decoction perfect for combating seasonal changes.", "ingredients": [{"name": "Tulsi leaves", "quantity": "10-12 leaves"}, {"name": "Fresh Ginger", "quantity": "1 inch piece"}, {"name": "Black Pepper", "quantity": "3-4 peppercorns"}, {"name": "Honey", "quantity": "1 tsp"}], "preparation_steps": ["Boil 2 cups water", "Add crushed tulsi leaves and grated ginger", "Add black pepper and let simmer for 10 minutes", "Strain and add honey when lukewarm", "Drink twice daily"], "preparation_method": "kashayam", "category": "respiratory", "dosha_balance": "Balances Kapha & Vata", "has_allergens": False, "allergens_list": [], "status": "approved", "source": "curated", "upvotes": 842},
    {"disease_name": "Sore Throat", "title": "Turmeric & Honey Throat Paste", "short_description": "Direct application remedy for sore throat using raw honey and turmeric.", "ingredients": [{"name": "Turmeric powder", "quantity": "1/2 tsp"}, {"name": "Raw Honey", "quantity": "1 tbsp"}], "preparation_steps": ["Mix turmeric with honey to form a paste", "Lick slowly to coat the throat", "Repeat 3-4 times daily"], "preparation_method": "paste", "category": "respiratory", "dosha_balance": "Balances Kapha", "has_allergens": True, "allergens_list": ["Honey"], "status": "approved", "source": "curated", "upvotes": 521},
    {"disease_name": "Sinus Congestion", "title": "Steam Inhalation with Eucalyptus", "short_description": "Clear nasal passages with herbal steam therapy.", "ingredients": [{"name": "Eucalyptus oil", "quantity": "3-4 drops"}, {"name": "Hot water", "quantity": "1 large bowl"}, {"name": "Ajwain seeds", "quantity": "1 tsp"}], "preparation_steps": ["Boil water and pour into a large bowl", "Add eucalyptus oil and ajwain seeds", "Drape a towel over your head and the bowl", "Inhale deeply for 10-15 minutes"], "preparation_method": "other", "category": "respiratory", "dosha_balance": "Balances Kapha", "status": "approved", "source": "curated", "upvotes": 315},
    {"disease_name": "Asthma", "title": "Black Pepper & Honey Brew", "short_description": "Traditional bronchodilator using warming spices.", "ingredients": [{"name": "Black Pepper", "quantity": "5 peppercorns"}, {"name": "Honey", "quantity": "2 tsp"}, {"name": "Warm water", "quantity": "1 glass"}], "preparation_steps": ["Crush black pepper finely", "Mix with warm water", "Add honey and stir", "Drink on empty stomach daily"], "preparation_method": "tea", "category": "respiratory", "dosha_balance": "Balances Kapha & Vata", "status": "approved", "source": "curated", "upvotes": 267},

    # ── Digestive ──
    {"disease_name": "Acid Reflux", "title": "Mint & Fennel Digestive Tea", "short_description": "Cooling digestive tea that reduces acid and soothes the stomach lining.", "ingredients": [{"name": "Fennel seeds", "quantity": "1 tsp"}, {"name": "Fresh Mint leaves", "quantity": "8-10 leaves"}, {"name": "Cumin seeds", "quantity": "1/2 tsp"}], "preparation_steps": ["Lightly crush fennel and cumin seeds", "Boil 1.5 cups of water", "Add all ingredients and steep for 8 minutes", "Strain and drink after meals"], "preparation_method": "tea", "category": "digestive", "dosha_balance": "Balances Pitta", "status": "approved", "source": "curated", "upvotes": 685},
    {"disease_name": "Constipation", "title": "Triphala Cleansing Drink", "short_description": "The most trusted Ayurvedic remedy for regular bowel movements.", "ingredients": [{"name": "Triphala powder", "quantity": "1 tsp"}, {"name": "Warm water", "quantity": "1 glass"}, {"name": "Honey", "quantity": "1/2 tsp (optional)"}], "preparation_steps": ["Add triphala powder to warm water", "Stir well and let stand for 2 minutes", "Drink before bedtime on empty stomach"], "preparation_method": "churna", "category": "digestive", "dosha_balance": "Balances all three doshas", "status": "approved", "source": "curated", "upvotes": 958},
    {"disease_name": "Bloating", "title": "Ajwain & Jeera Water", "short_description": "Quick-acting carminative that relieves gas and bloating within minutes.", "ingredients": [{"name": "Ajwain (carom seeds)", "quantity": "1 tsp"}, {"name": "Cumin seeds", "quantity": "1 tsp"}, {"name": "Black salt", "quantity": "a pinch"}], "preparation_steps": ["Dry roast ajwain and cumin on low heat", "Crush lightly", "Mix with warm water and a pinch of black salt", "Drink immediately after meals"], "preparation_method": "other", "category": "digestive", "dosha_balance": "Balances Vata & Kapha", "status": "approved", "source": "curated", "upvotes": 432},
    {"disease_name": "Indigestion", "title": "Ginger Lemon Digestive Shot", "short_description": "Pre-meal appetite stimulant used across Indian households.", "ingredients": [{"name": "Fresh Ginger juice", "quantity": "1 tsp"}, {"name": "Lemon juice", "quantity": "1 tsp"}, {"name": "Rock salt", "quantity": "a pinch"}], "preparation_steps": ["Extract fresh ginger juice", "Mix with lemon juice", "Add a pinch of rock salt", "Take 15 minutes before meals"], "preparation_method": "other", "category": "digestive", "dosha_balance": "Kindles Agni (digestive fire)", "status": "approved", "source": "curated", "upvotes": 378},

    # ── Skin & Hair ──
    {"disease_name": "Acne", "title": "Neem & Turmeric Face Pack", "short_description": "Antibacterial paste for active acne using neem and turmeric.", "ingredients": [{"name": "Neem powder", "quantity": "1 tbsp"}, {"name": "Turmeric powder", "quantity": "1/2 tsp"}, {"name": "Rosewater", "quantity": "enough to make paste"}], "preparation_steps": ["Mix neem powder and turmeric", "Add rosewater gradually to form a smooth paste", "Apply evenly on affected areas", "Leave for 20 minutes, then wash with cold water"], "preparation_method": "lepa", "category": "skin_hair", "dosha_balance": "Balances Pitta & Kapha", "status": "approved", "source": "curated", "upvotes": 719},
    {"disease_name": "Hair Fall", "title": "Amla & Coconut Oil Scalp Treatment", "short_description": "Strengthens hair roots and reduces fall with Vitamin C rich treatment.", "ingredients": [{"name": "Amla powder", "quantity": "2 tbsp"}, {"name": "Coconut oil", "quantity": "100ml"}, {"name": "Curry leaves", "quantity": "10-12 leaves"}], "preparation_steps": ["Heat coconut oil on low flame", "Add amla powder and curry leaves", "Cook on very low heat for 15 minutes", "Cool, strain, and store in a glass bottle", "Massage into scalp 30 minutes before washing"], "preparation_method": "taila", "category": "skin_hair", "dosha_balance": "Balances Pitta", "status": "approved", "source": "curated", "upvotes": 634},
    {"disease_name": "Dry Skin", "title": "Almond Milk & Saffron Body Pack", "short_description": "Luxurious moisturizing treatment for dry, flaky winter skin.", "ingredients": [{"name": "Almond paste", "quantity": "2 tbsp"}, {"name": "Milk", "quantity": "2 tbsp"}, {"name": "Saffron strands", "quantity": "4-5 strands"}], "preparation_steps": ["Soak saffron in warm milk for 10 minutes", "Mix with almond paste", "Apply on body and face", "Leave for 20 minutes, rinse with lukewarm water"], "preparation_method": "lepa", "category": "skin_hair", "dosha_balance": "Balances Vata", "has_allergens": True, "allergens_list": ["Dairy", "Nuts"], "status": "approved", "source": "curated", "upvotes": 289},

    # ── Mental Health ──
    {"disease_name": "Insomnia", "title": "Ashwagandha Restful Milk", "short_description": "Adaptogenic nightcap that calms the nervous system for deep sleep.", "ingredients": [{"name": "Ashwagandha powder", "quantity": "1/2 tsp"}, {"name": "Warm Milk", "quantity": "1 glass"}, {"name": "Nutmeg powder", "quantity": "a pinch"}, {"name": "Honey", "quantity": "1 tsp"}], "preparation_steps": ["Warm the milk (do not boil)", "Add ashwagandha and nutmeg powder", "Stir well", "Add honey once slightly cooled", "Drink 30 minutes before sleep"], "preparation_method": "other", "category": "mental_health", "dosha_balance": "Balances Vata", "has_allergens": True, "allergens_list": ["Dairy"], "status": "approved", "source": "curated", "upvotes": 1012},
    {"disease_name": "Anxiety", "title": "Brahmi & Shankhpushpi Calm Drink", "short_description": "Brain-calming nootropic herbs that reduce anxiety and improve focus.", "ingredients": [{"name": "Brahmi powder", "quantity": "1/2 tsp"}, {"name": "Shankhpushpi powder", "quantity": "1/2 tsp"}, {"name": "Warm water", "quantity": "1 glass"}, {"name": "Honey", "quantity": "1 tsp"}], "preparation_steps": ["Mix both powders in warm water", "Stir thoroughly", "Add honey when lukewarm", "Drink twice daily — morning and evening"], "preparation_method": "churna", "category": "mental_health", "dosha_balance": "Balances Vata & Pitta", "status": "approved", "source": "curated", "upvotes": 567},
    {"disease_name": "Stress", "title": "Golden Milk (Haldi Doodh)", "short_description": "India's original wellness latte — anti-inflammatory and deeply calming.", "ingredients": [{"name": "Turmeric powder", "quantity": "1 tsp"}, {"name": "Black Pepper", "quantity": "a pinch"}, {"name": "Warm Milk", "quantity": "1 glass"}, {"name": "Ghee", "quantity": "1/2 tsp"}, {"name": "Jaggery", "quantity": "to taste"}], "preparation_steps": ["Warm milk on medium heat", "Add turmeric and black pepper", "Stir continuously for 3 minutes", "Add ghee and jaggery", "Drink warm before bed"], "preparation_method": "other", "category": "mental_health", "dosha_balance": "Balances Vata & Kapha", "has_allergens": True, "allergens_list": ["Dairy"], "status": "approved", "source": "curated", "upvotes": 1342},

    # ── Bones & Muscles ──
    {"disease_name": "Joint Pain", "title": "Turmeric Golden Milk", "short_description": "Warm comforting drink that reduces joint inflammation.", "ingredients": [{"name": "Turmeric powder", "quantity": "1 tsp"}, {"name": "Black Pepper", "quantity": "a pinch"}, {"name": "Warm Milk", "quantity": "1 glass"}], "preparation_steps": ["Warm milk but don't boil", "Add turmeric and pepper", "Stir well and drink before sleep"], "preparation_method": "other", "category": "bones_muscles", "dosha_balance": "Balances Vata & Kapha", "has_allergens": True, "allergens_list": ["Dairy"], "status": "approved", "source": "curated", "upvotes": 842},
    {"disease_name": "Muscle Pain", "title": "Mahanarayan Oil Massage", "short_description": "Traditional medicated oil for deep muscle pain relief.", "ingredients": [{"name": "Mahanarayan oil", "quantity": "2 tbsp"}, {"name": "Sesame oil", "quantity": "1 tbsp"}], "preparation_steps": ["Warm the oil blend slightly", "Massage firmly into the affected area", "Leave for 30-45 minutes", "Follow with a warm shower"], "preparation_method": "taila", "category": "bones_muscles", "dosha_balance": "Balances Vata", "status": "approved", "source": "curated", "upvotes": 456},

    # ── Women's Health ──
    {"disease_name": "Menstrual Cramps", "title": "Ajwain & Jaggery Hot Water", "short_description": "Time-tested remedy for period pain used across Indian households.", "ingredients": [{"name": "Ajwain seeds", "quantity": "1 tsp"}, {"name": "Jaggery", "quantity": "1 tbsp"}, {"name": "Hot water", "quantity": "1 glass"}], "preparation_steps": ["Dry roast ajwain seeds lightly", "Add to hot water with jaggery", "Stir until dissolved", "Sip slowly during cramps"], "preparation_method": "kashayam", "category": "womens_health", "dosha_balance": "Balances Vata", "status": "approved", "source": "curated", "upvotes": 723},

    # ── Eye Health ──
    {"disease_name": "Eye Strain", "title": "Triphala Eye Wash", "short_description": "Cooling eye wash to relieve digital eye strain and redness.", "ingredients": [{"name": "Triphala powder", "quantity": "1 tsp"}, {"name": "Clean water", "quantity": "1 cup"}], "preparation_steps": ["Soak triphala in water overnight", "Strain through a fine cloth in the morning", "Use the clear water as an eye wash", "Repeat daily for 2 weeks"], "preparation_method": "other", "category": "eye_health", "dosha_balance": "Balances Pitta", "status": "approved", "source": "curated", "upvotes": 234},

    # ── Immunity ──
    {"disease_name": "Low Immunity", "title": "Chyawanprash Daily Tonic", "short_description": "The king of Ayurvedic rasayanas for year-round immunity.", "ingredients": [{"name": "Chyawanprash", "quantity": "1 tbsp"}, {"name": "Warm Milk", "quantity": "1 glass (optional)"}], "preparation_steps": ["Take 1 tablespoon of chyawanprash", "Eat directly or mix with warm milk", "Take daily — morning on empty stomach"], "preparation_method": "other", "category": "immunity", "dosha_balance": "Balances all doshas", "has_allergens": True, "allergens_list": ["Dairy"], "status": "approved", "source": "curated", "upvotes": 1456},
    {"disease_name": "Fever", "title": "Coriander Seed Decoction", "short_description": "Traditional fever reducer using cooling coriander seeds.", "ingredients": [{"name": "Coriander seeds", "quantity": "2 tsp"}, {"name": "Water", "quantity": "2 cups"}, {"name": "Jaggery", "quantity": "to taste"}], "preparation_steps": ["Soak coriander seeds in water for 1 hour", "Boil until reduced to half", "Strain and add jaggery", "Drink 3 times daily while feverish"], "preparation_method": "kashayam", "category": "immunity", "dosha_balance": "Balances Pitta", "status": "approved", "source": "curated", "upvotes": 345},

    # ── Oral Health ──
    {"disease_name": "Toothache", "title": "Clove Oil Direct Application", "short_description": "Instant numbing relief for toothache using clove's eugenol compound.", "ingredients": [{"name": "Clove oil", "quantity": "2-3 drops"}, {"name": "Cotton ball", "quantity": "1"}], "preparation_steps": ["Apply 2-3 drops of clove oil on cotton", "Place directly on the aching tooth", "Hold for 15-20 minutes", "Reapply as needed"], "preparation_method": "other", "category": "oral_health", "dosha_balance": "Balances Kapha & Vata", "status": "approved", "source": "curated", "upvotes": 567},

    # ── Diabetes ──
    {"disease_name": "High Blood Sugar", "title": "Fenugreek Soaked Water", "short_description": "Blood sugar regulating fenugreek therapy backed by modern research.", "ingredients": [{"name": "Fenugreek seeds", "quantity": "2 tsp"}, {"name": "Water", "quantity": "1 glass"}], "preparation_steps": ["Soak fenugreek seeds in water overnight", "Drink the water on empty stomach in the morning", "Chew the soaked seeds as well", "Continue daily for best results"], "preparation_method": "other", "category": "metabolic", "dosha_balance": "Balances Kapha", "status": "approved", "source": "curated", "upvotes": 489},

    # ── Heart Health ──
    {"disease_name": "High Cholesterol", "title": "Garlic & Lemon Morning Tonic", "short_description": "Heart-protective morning drink combining garlic's allicin with vitamin C.", "ingredients": [{"name": "Garlic cloves", "quantity": "2 cloves"}, {"name": "Lemon juice", "quantity": "1/2 lemon"}, {"name": "Warm water", "quantity": "1 glass"}, {"name": "Honey", "quantity": "1 tsp"}], "preparation_steps": ["Crush garlic and let sit for 5 minutes (activates allicin)", "Add to warm water with lemon juice", "Add honey and stir", "Drink every morning on empty stomach"], "preparation_method": "other", "category": "heart_health", "dosha_balance": "Balances Kapha", "status": "approved", "source": "curated", "upvotes": 612},

    # ── Kidney ──
    {"disease_name": "Kidney Stones", "title": "Banana Stem Juice Detox", "short_description": "Traditional South Indian remedy to dissolve small kidney stones.", "ingredients": [{"name": "Banana stem (inner fiber)", "quantity": "1 cup chopped"}, {"name": "Cardamom", "quantity": "2 pods"}, {"name": "Water", "quantity": "1/2 cup"}], "preparation_steps": ["Extract juice from banana stem using a blender", "Add crushed cardamom", "Drink fresh, twice daily", "Continue for 2-3 weeks"], "preparation_method": "other", "category": "kidney", "dosha_balance": "Balances Pitta & Kapha", "status": "approved", "source": "curated", "upvotes": 298},
]


async def seed_remedies():
    """Seed remedies into the database."""
    await init_db()

    existing = await Remedy.count()
    if existing > 0:
        print(f"[SKIP] {existing} remedies already exist. Skipping seed.")
        return

    for data in REMEDIES_DATA:
        ingredients = [Ingredient(**ing) for ing in data.pop("ingredients")]
        remedy = Remedy(**data, ingredients=ingredients)
        await remedy.insert()

    print(f"[OK] Seeded {len(REMEDIES_DATA)} remedies")


if __name__ == "__main__":
    asyncio.run(seed_remedies())
